#!/bin/bash
# Generates inventory/host_vars/piwheels-master.yml from hostedpi.
# Run this whenever the master's SSH address may have changed.
set -e

HOST=$(hostedpi info ssh-hostname piwheels)
PORT=$(hostedpi info ssh-port piwheels)
DEST="$(dirname "$0")/../inventory/host_vars/piwheels-master.yml"

cat > "$DEST" <<EOF
# Generated by scripts/update-master-vars.sh — do not commit
ansible_host: $HOST
ansible_port: $PORT
ansible_user: root
EOF

echo "Written $DEST (host=$HOST port=$PORT)"
