all:
  children:
    piwheels_master:
      hosts:
        piwheels-master:
    piwheels_slaves:
      children:
        cp311:
          hosts:
            pw-slave-cp311-01:
              ansible_host: ssh.pw-slave-cp311-01.hostedpi.com
              ansible_port: 5359
            pw-slave-cp311-02:
              ansible_host: ssh.pw-slave-cp311-02.hostedpi.com
              ansible_port: 5333
            pw-slave-cp311-03:
              ansible_host: ssh.pw-slave-cp311-03.hostedpi.com
              ansible_port: 5212
            pw-slave-cp311-04:
              ansible_host: ssh.pw-slave-cp311-04.hostedpi.com
              ansible_port: 5222
            pw-slave-cp311-05:
              ansible_host: ssh.pw-slave-cp311-05.hostedpi.com
              ansible_port: 5315
            pw-slave-cp311-06:
              ansible_host: ssh.pw-slave-cp311-06.hostedpi.com
              ansible_port: 5280
        cp313:
          hosts:
            pw-slave-cp313-01:
              ansible_host: ssh.pw-slave-cp313-01.hostedpi.com
              ansible_port: 5377
            pw-slave-cp313-02:
              ansible_host: ssh.pw-slave-cp313-02.hostedpi.com
              ansible_port: 5193
            pw-slave-cp313-03:
              ansible_host: ssh.pw-slave-cp313-03.hostedpi.com
              ansible_port: 5301
            pw-slave-cp313-04:
              ansible_host: ssh.pw-slave-cp313-04.hostedpi.com
              ansible_port: 5382
            pw-slave-cp313-05:
              ansible_host: ssh.pw-slave-cp313-05.hostedpi.com
              ansible_port: 5196
            pw-slave-cp313-06:
              ansible_host: ssh.pw-slave-cp313-06.hostedpi.com
              ansible_port: 5208
            pw-slave-cp313-07:
              ansible_host: ssh.pw-slave-cp313-07.hostedpi.com
              ansible_port: 5289
            pw-slave-cp313-08:
              ansible_host: ssh.pw-slave-cp313-08.hostedpi.com
              ansible_port: 5231
            pw-slave-cp313-09:
              ansible_host: ssh.pw-slave-cp313-09.hostedpi.com
              ansible_port: 5200
            pw-slave-cp313-10:
              ansible_host: ssh.pw-slave-cp313-10.hostedpi.com
              ansible_port: 5247
        cp39:
          hosts:
            pw-slave-cp39-01:
              ansible_host: ssh.pw-slave-cp39-01.hostedpi.com
              ansible_port: 5293
            pw-slave-cp39-02:
              ansible_host: ssh.pw-slave-cp39-02.hostedpi.com
              ansible_port: 5287
            pw-slave-cp39-03:
              ansible_host: ssh.pw-slave-cp39-03.hostedpi.com
              ansible_port: 5249
            pw-slave-cp39-04:
              ansible_host: ssh.pw-slave-cp39-04.hostedpi.com
              ansible_port: 5205
            pw-slave-cp39-05:
              ansible_host: ssh.pw-slave-cp39-05.hostedpi.com
              ansible_port: 5338
