FROM debian:buster

RUN apt update
RUN apt install -y python3 python3-pip python3-setuptools python3-wheel \
    python3-configargparse python3-zmq python3-voluptuous python3-dateutil \
    python3-pytest python3-pytest-cov python3-apt python3-requests python3-psycopg2 \
    python3-chameleon python3-simplejson python3-pygeoip
RUN addgroup --system piwheels && adduser --system --ingroup piwheels piwheels

COPY . /app
WORKDIR /app

RUN pip3 install . --no-deps
RUN pip3 install packaging cbor2 lars sqlalchemy==1.4

RUN addgroup --system piwheels && \
    adduser --system --ingroup piwheels --shell /bin/bash --home /home/piwheels piwheels && \
    mkdir -p /home/piwheels && \
    chown piwheels:piwheels /home/piwheels
    
USER piwheels
WORKDIR /app