FROM debian:bookworm

RUN apt update && apt install -y apache2

COPY ./docker/apache/000-default.conf /etc/apache2/sites-available/000-default.conf

RUN a2enmod rewrite && service apache2 restart
RUN echo "ServerName localhost" > /etc/apache2/conf-available/servername.conf && a2enconf servername

EXPOSE 80

CMD ["apachectl", "-D", "FOREGROUND"]