FROM debian:bookworm

RUN apt update
RUN apt install -y --fix-missing python3 python3-pip python3-setuptools python3-wheel \
    python3-simplejson python3-sphinx python3-sphinx-rtd-theme inkscape

COPY . /app
WORKDIR /app

RUN pip3 install . --break-system-packages --no-deps
RUN pip3 install lars --break-system-packages