FROM debian:bookworm

RUN apt update
RUN apt install -y python3 python3-pip python3-setuptools python3-wheel python3-packaging \
    python3-configargparse python3-zmq python3-voluptuous python3-cbor2 python3-dateutil \
    python3-pytest python3-apt
RUN addgroup --system piwheels && adduser --system --ingroup piwheels piwheels

WORKDIR /app

COPY . .

RUN pip3 install ".[master,logger,test]" --break-system-packages

USER piwheels