FROM debian:bookworm

RUN apt update
RUN apt install -y python3 python3-pip python3-setuptools python3-wheel python3-packaging \
    python3-configargparse python3-zmq python3-voluptuous python3-cbor2 python3-dateutil \
    python3-requests python3-sqlalchemy python3-psycopg2 python3-chameleon \
    python3-simplejson

COPY . /app
WORKDIR /app

RUN pip3 install . --break-system-packages