name: Run Tests in Docker

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build container images
        run: docker compose build db test-bullseye test-bookworm

      - name: Run tests on Debian Bullseye (Python 3.9)
        run: docker compose run --rm test-bullseye

      - name: Run tests on Debian Bookworm (Python 3.11)
        run: docker compose run --rm test-bookworm

      - name: Run tests on Debian Trixie (Python 3.13)
        run: docker compose run --rm test-trixie

      - name: Shut down services
        run: docker compose down
